# docker-compose.yml

services:
  backend:
    build: ./back-end         
    container_name: skkuedin-backend 
    env_file:
      - ./back-end/.env       
    volumes:
      - db_data:/data
      - ./front-end/public:/front-end/public:ro
      - ./front-end/public/images:/app/images:ro
    ports:
      - "8000:8000"            
    
  frontend:
    build: ./front-end         
    container_name: skkuedin-frontend 
    ports:
      - "80:80"            # 호스트(EC2) 80 포트 -> 컨테이너 80 포트 (Nginx)
    depends_on:
      - backend

  crawler:
    build: ./contest-crawler
    container_name: skkuedin-crawler
    shm_size: '2gb'
    environment:
      - DATABASE_URL=sqlite:////data/test.db
    # env_file:
    #   - ./back-end/.env
    depends_on:
      - backend
    volumes:
      - db_data:/data
      - ./back-end/app:/app/app             

volumes:
  db_data:  # 컨테이너 재시작되어도 보존
