# docker-compose.yml

services:
  backend:
    build: ./back-end         
    container_name: skkuedin-backend 
    env_file:
      - ./back-end/.env       
    volumes:
      - ./back-end/skkuedin.db:/app/app.db
      - ./front-end/public:/front-end/public:ro
    environment:
      - DATABASE_URL=sqlite:////app/app.db
    ports:
      - "8000:8000"            
    
  frontend:
    build: ./front-end         
    container_name: skkuedin-frontend 
    ports:
      - "80:80"            # 호스트(EC2) 80 포트 -> 컨테이너 80 포트 (Nginx)
    depends_on:
      - backend             